sudo: false
language: perl
perl:
  - "5.22@moo"
  - "5.20@moo"
  - "5.18@moo"
  - "5.16@moo"
  - "5.14@moo"
  - "5.12@moo"
matrix:
  include:
    - perl: "5.24@moo"
      env: COVERAGE=1
before_install:
  - git config --global github.user mjgardner
  - eval $(curl https://travis-perl.github.io/init) --auto
