sudo: false
language: perl
perl:
  - 5.22.2
  - 5.20.3
  - 5.18.4
  - 5.16.3
  - 5.14.4
  - 5.12.5
matrix:
  include:
    - perl: 5.24.0
      env: COVERAGE=1
before_install:
  - git config --global github.user mjgardner
  - eval $(curl https://travis-perl.github.io/init) --auto
