sudo: false
language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1
addons:
  apt:
    packages:
      - unzip
before_install:
  - git config --global github.user mjgardner
  - eval $(curl https://travis-perl.github.io/init) --auto
