language: perl
perl:
  - 5.24
  - 5.22
  - 5.20
  - 5.18
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq unzip
  - git config --global github.user mjgardner
  - cpanm Dist::Zilla
  - dzil authordeps | xargs cpanm --verbose
install: dzil listdeps | xargs cpanm --verbose
script: dzil test --all --verbose
