sudo: false
language: perl
perl:
  - "5.22@moo"
  - "5.20@moo"
  - "5.18@moo"
  - "5.16@moo"
  - "5.14@moo"
  - "5.12@moo"
env:
  secure: "LZoWXHKHdC0ceYJljIv+WB9m0N7qaoLrYdxZRswcMoQW9EGVlIWoUmnD5CWoW25gQ+hTGD7wZLI+7fy4MsWJiFufwjVnqy3GzNDPv2J0atPZ3zGYOIVlongxWmzlqt4Bdug9Vlp99J7AI1//KBmV8BRkLg2mibDkySE4IEh5xMY="
matrix:
  include:
    - perl: "5.24@moo"
      env:
        - COVERAGE=1
        - secure: "LZoWXHKHdC0ceYJljIv+WB9m0N7qaoLrYdxZRswcMoQW9EGVlIWoUmnD5CWoW25gQ+hTGD7wZLI+7fy4MsWJiFufwjVnqy3GzNDPv2J0atPZ3zGYOIVlongxWmzlqt4Bdug9Vlp99J7AI1//KBmV8BRkLg2mibDkySE4IEh5xMY="
before_install:
  - git config --global github.user mjgardner
  - git config --global github.password ${GITHUB_TRAVIS_TOKEN:?}
  - eval $(curl -u mjgardner:${GITHUB_TRAVIS_TOKEN:?} https://travis-perl.github.io/init) --auto
